kind: pipeline
type: kubernetes
name: Build

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: test
    image: golang:1.14.1
    commands:
      - wget -qO- https://github.com/lukaspj/ecmake/releases/download/v0.0.3/ecmake_0.0.3_Linux_x86_64.tar.gz | tar -xz ecmake && mv ecmake /usr/local/bin/
      - ecmake TestWithRace

  - name: release
    image: goreleaser/goreleaser
    volumes:
        - name: dockersock
          path: /var/run
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
      - goreleaser release
    environment:
      GITHUB_TOKEN:
        from_secret: github-token
      DOCKER_REGISTRY: docker.pkg.github.com
      DOCKER_USERNAME: lukaspj
      DOCKER_PASSWORD:
        from_secret: github-packages-token
    when:
      event:
        - tag

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

---
kind: secret
name: github-token
get:
  path: github-repo-token
  name: repotoken
---
kind: secret
name: github-packages-token
get:
  path: github-repo-token
  name: packagetoken

