kind: pipeline
type: kubernetes
name: Build

anchors:
  - &build_and_push_docker
    image: plugins/docker
    settings:
      registry: docker.pkg.github.com
      username: lukaspj
      password:
        from_secret: github-packages-token
  - &build_and_push_docker_go_1_14
    <<: *build_and_push_docker
    settings:
      repo: docker.pkg.github.com/lukaspj/ecmake/go_1_14
      dockerfile: docker/go1.14.Dockerfile
  - &build_and_push_docker_scratch
    <<: *build_and_push_docker
    settings:
      repo: docker.pkg.github.com/lukaspj/ecmake/scratch
      dockerfile: docker/scratch.Dockerfile

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: test
    image: golang:1.14.1
    commands:
      - wget -qO- https://github.com/lukaspj/ecmake/releases/download/v0.0.3/ecmake_0.0.3_Linux_x86_64.tar.gz | tar -xz ecmake && mv ecmake /usr/local/bin/
      - ecmake TestWithRace

  - name: release
    image: goreleaser/goreleaser
    commands:
      - goreleaser release
    environment:
      GITHUB_TOKEN:
        from_secret: github-token
    when:
      event:
        - tag

  - name: docker publish master
    <<: *build_and_push_docker_scratch
    settings:
      tags:
        - master
    when:
      branch:
        - master

  - name: docker publish Go master
    <<: *build_and_push_docker_go_1_14
    settings:
      tags:
        - master-go1.14
    when:
      branch:
        - master

  - name: docker publish release
    <<: *build_and_push_docker_scratch
    settings:
      tags:
        - ${DRONE_SEMVER_MAJOR}
        - ${DRONE_SEMVER}
        - latest
    when:
      event:
        - tag

  - name: docker publish Go release
    <<: *build_and_push_docker_go_1_14
    settings:
      tags:
        - ${DRONE_SEMVER_MAJOR}-go1.14
        - ${DRONE_SEMVER}-go1.14
        - go1.14
    when:
      event:
        - tag

---
kind: secret
name: github-token
get:
  path: github-repo-token
  name: repotoken
---
kind: secret
name: github-packages-token
get:
  path: github-repo-token
  name: packagetoken

