kind: pipeline
type: kubernetes
name: Build

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: test
    image: golang:1.14.1
    commands:
      - go test -race -v ./... -cover

  - name: release
    image: golang:1.14.1
    commands:
      - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
    environment:
      GITHUB_TOKEN:
        from_secret: github-token
    when:
      event:
        - tag


---
kind: secret
name: github-token
get:
  path: github-repo-token
  name: token

